Add.o : Add.c pch.h
	gcc -fPIC -c -o Add.o Add.c

Category.o : Category.c pch.h
	gcc -fPIC -c -o Category.o Category.c

Create.o : Create.c pch.h
	gcc -fPIC -c Create.c

Exit.o : Exit.c pch.h
	gcc -fPIC -c Exit.c

Find.o : Find.c pch.h
	gcc -fPIC -c Find.c

MainMenu.o : MainMenu.c pch.h
	gcc -fPIC -c MainMenu.c

PrintAll.o : PrintAll.c pch.h
	gcc -fPIC -c PrintAll.c 

Reallocation.o : Reallocation.c pch.h
	gcc -fPIC -c Reallocation.c

Remove.o : Remove.c pch.h
	gcc -fPIC -c Remove.c

Search.o : Search.c pch.h
	gcc -fPIC -c Search.c

UI.o : UI.c pch.h
	gcc -fPIC -c UI.c

Update.o : Update.c pch.h
	gcc -fPIC -c Update.c

clean: 
	rm -rf *.o